Small plugin for jump. Also adds check for NNN_PIPE to autojump plugin (#714)
* Add jump plugin to nnn

* indents

* Readme for plugin

* add pipe check to autojump

* indents to 4

Merge plugins jump and autojump

diff --git a/plugins/autojump b/plugins/autojump
--- a/plugins/autojump
+++ b/plugins/autojump
@@ -1,20 +1,31 @@
 #!/usr/bin/env sh
 
-# Description: Navigate to directory using autojump
+# Description: Navigate to directory using jump/autojump
 #
-# Dependencies: autojump - https://github.com/wting/autojump
+# Dependencies: jump - https://github.com/gsamokovarov/jump
+#               OR autojump - https://github.com/wting/autojump
 #
-# Note: autojump STORES NAVIGATION PATTERNS
+# Note: jump/autojump STORES NAVIGATION PATTERNS
 #
 # Shell: POSIX compliant
-# Author: Marty Buchaus
+# Authors: Marty Buchaus, Dave Snider
 
-if which autojump >/dev/null 2>&1; then
+if [ -z "$NNN_PIPE" ]; then
+    echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
+    exit 2
+fi
+
+if which jump >/dev/null 2>&1; then
+    printf "jump to: "
+    read -r dir
+    odir="$(jump cd "$dir")"
+    printf "%s" "0c$odir" > "$NNN_PIPE"
+elif which autojump >/dev/null 2>&1; then
     printf "jump to: "
     read -r dir
     odir="$(autojump "$dir")"
     printf "%s" "0c$odir" > "$NNN_PIPE"
 else
-    printf "autojump missing"
+    printf "jump/autojump missing"
     read -r _
 fi
