indents to 4

diff --git a/plugins/autojump b/plugins/autojump
--- a/plugins/autojump
+++ b/plugins/autojump
@@ -10,8 +10,8 @@
 # Author: Marty Buchaus
 
 if [ -z "$NNN_PIPE" ]; then
-  echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
-  exit 2
+    echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
+    exit 2
 fi
 
 if which autojump >/dev/null 2>&1; then
diff --git a/plugins/jump b/plugins/jump
--- a/plugins/jump
+++ b/plugins/jump
@@ -10,16 +10,16 @@
 # Author: Dave Snider
 
 if [ -z "$NNN_PIPE" ]; then
-  echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
-  exit 2
+    echo 'ERROR: NNN_PIPE is not set' | ${PAGER:-less}
+    exit 2
 fi
 
 if which jump >/dev/null 2>&1; then
-  printf "jump to: "
-  read -r dir
-  odir="$(jump cd "$dir")"
-  printf "%s" "0c$odir" > "$NNN_PIPE"
+    printf "jump to: "
+    read -r dir
+    odir="$(jump cd "$dir")"
+    printf "%s" "0c$odir" > "$NNN_PIPE"
 else
-  printf "jump missing"
-  read -r _
+    printf "jump missing"
+    read -r _
 fi
