Exit if cmus missing and style changes

diff --git a/plugins/cmusq b/plugins/cmusq
--- a/plugins/cmusq
+++ b/plugins/cmusq
@@ -19,68 +19,61 @@
 # or leave commented out to use OS default
 #TERMINAL="kitty"
 
+if ! type cmus >/dev/null; then
+    printf "cmus missing"
+    read -r _
+fi
+
 # Required variables
 selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
-REPLY=c
 
 start_cmus() {
-    if type xdotool >/dev/null; then
-        nnnwindow="$(xdotool getactivewindow)"
-    fi
-    printf "cmus is not running, starting it in a new %s window.\n" "$TERMINAL"
-    (case "$TERMINAL" in
+    type xdotool >/dev/null && nnnwindow="$(xdotool getactivewindow)"
+    case "$TERMINAL" in
         kitty | gnome-terminal | st)
-            nohup "$TERMINAL" -- cmus >/dev/null 2>&1 &
-            ;;
+            nohup "$TERMINAL" -- cmus & ;;
         havoc)
-            nohup "$TERMINAL" cmus >/dev/null 2>&1 &
-            ;;
+            nohup "$TERMINAL" cmus & ;;
         "")
-            nohup x-terminal-emulator -e cmus >/dev/null 2>&1 &
-            ;;
+            nohup x-terminal-emulator -e cmus & ;;
         *)
-            nohup "$TERMINAL" -e cmus >/dev/null 2>&1 &
-            ;;
-    esac)
-    until pidof cmus >/dev/null; do sleep 0.1; done # Give the new terminal some time to open
-    if type xdotool >/dev/null; then
-        xdotool windowactivate "$nnnwindow"
-    fi
+            nohup "$TERMINAL" -e cmus & ;;
+    esac
+    # Give the new terminal some time to open
+    until pidof cmus >/dev/null; do sleep 0.1; done
+    [ -n "$nnnwindow" ] && xdotool windowactivate "$nnnwindow"
+} >/dev/null 2>&1
+
+fill_queue() {
+  if [ "$REPLY" = "s" ]; then
+      xargs < "$selection" -0 cmus-remote -q
+  elif [ -n "$1" ]; then
+      cmus-remote -q "$1"
+  fi
 }
 
-# If active selection,then  ask what to do
+# If active selection,then ask what to do
 if [ -s "$selection" ]; then
     printf "Queue [s]election or [c]urrently hovered? [default=c]: "
     read -r REPLY
 fi
 
-# If [s]election, then start cmus in new window (if necessary) and append selection to queue
-if [ "$REPLY" = "s" ]; then
-    if ! pgrep cmus >/dev/null; then
-        start_cmus
-        printf "Files added to cmus queue.\n"
-        # Queue, change view and play
-        cmus-remote -C "view 4"; xargs < "$selection" -0 cmus-remote -q; cmus-remote -p
-    else
-        # Queue in existing cmus if already running and change view
-        printf "Files added to current cmus queue.\n"
-        cmus-remote -C "view 4"; xargs < "$selection" -0 cmus-remote -q
-    fi
-    # Clear selection
-    if [ -p "$NNN_PIPE" ]; then
-        printf "-" > "$NNN_PIPE"
-    fi
+# If cmus is not running, start and play queue
+if ! pgrep cmus >/dev/null; then
+    printf "cmus is not running, starting it in a new %s window.\n" "$TERMINAL"
+    start_cmus
+    fill_queue "$1"
+    cmus-remote -p
+    printf "Files added to cmus queue.\n"
+else # Append to existing queue if cmus is already running
+    fill_queue "$1"
+    printf "Files appended to current cmus queue.\n"
+fi
 
-# If [c]urrent, then start cmus in new window (if necessary) and append hovered file or directory to queue
-elif [ -n "$1" ]; then
-    if ! pgrep cmus >/dev/null; then
-        start_cmus
-        printf "'%s' added to cmus queue.\n" "$1"
-        # Queue, change view and play
-        cmus-remote -C "view 4"; cmus-remote -q "$1"; cmus-remote -p
-    else
-        # Queue in existing cmus if already running and change view
-        printf "'%s' added to current cmus queue.\n" "$1"
-        cmus-remote -C "view 4"; cmus-remote -q "$1"
-    fi
+# Change view
+cmus-remote -C "view 4"
+
+# Clear selection
+if [ -p "$NNN_PIPE" ]; then
+    printf "-" > "$NNN_PIPE"
 fi
