Refresh dirs on disruptive chnages, update sxiv plugin to browse and rename

diff --git a/plugins/sxiv b/plugins/sxiv
--- a/plugins/sxiv
+++ b/plugins/sxiv
@@ -1,8 +1,20 @@
 #!/usr/bin/env sh
 
-# Description: Open images in current directory in sxiv
+# Description: Open images in hovered  directory and thumbnails
+#              open hovered image in sxiv and browse other images in the directory
 #
 # Shell: POSIX compliant
 # Author: Arun Prakash Jana
 
-sxiv -q * >/dev/null 2>&1 &
+if command -v sxiv >/dev/null 2>&1; then
+    if ! [ -z "$1" ]; then
+        if [ -f "$1" ]; then
+            sxiv -q "$PWD"
+        elif [ -d "$1" ] || [ -h "$1" ]; then
+            sxiv -qt "$1"
+        fi
+    fi
+else
+    echo "sxiv missing"
+    read dummy
+fi
